In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
pf = files.upload()

Saving SuperStore Sales DataSet.csv to SuperStore Sales DataSet (2).csv


In [ ]:
pf = pd.read_csv("SuperStore Sales DataSet (2).csv",encoding = 'latin1')
pf

Row ID+O6G3A1:R6        Order ID  Order Date   Ship Date  \
0                 4918  CA-2019-160304  01-01-2019  07-01-2019   
1                 4919  CA-2019-160304  02-01-2019  07-01-2019   
2                 4920  CA-2019-160304  02-01-2019  07-01-2019   
3                 3074  CA-2019-125206  03-01-2019  05-01-2019   
4                 8604  US-2019-116365  03-01-2019  08-01-2019   
...                ...             ...         ...         ...   
5896               907  CA-2020-143259  30-12-2020  03-01-2021   
5897              1297  CA-2020-115427  30-12-2020  03-01-2021   
5898              5092  CA-2020-156720  30-12-2020  03-01-2021   
5899               909  CA-2020-143259  30-12-2020  03-01-2021   
5900              5093  CA-2020-151450  31-12-2020  04-01-2021   

           Ship Mode Customer ID      Customer Name    Segment        Country  \
0     Standard Class    BM-11575      Brendan Murry  Corporate  United States   
1     Standard Class    BM-11575      Brendan Murry  Corporate  United States   
2     Standard Class    BM-11575      Brendan Murry  Corporate  United States   
3        First Class    LR-16915       Lena Radford   Consumer  United States   
4     Standard Class    CA-12310  Christine Abelman  Corporate  United States   
...              ...         ...                ...        ...            ...   
5896  Standard Class    PO-18865  Patrick O'Donnell   Consumer  United States   
5897  Standard Class    EB-13975         Erica Bern  Corporate  United States   
5898  Standard Class    JM-15580      Jill Matthias   Consumer  United States   
5899  Standard Class    PO-18865  Patrick O'Donnell   Consumer  United States   
5900  Standard Class    JM-15580      Jill Matthias   Consumer  United States   

               City  ...         Category Sub-Category  \
0      Gaithersburg  ...        Furniture    Bookcases   
1      Gaithersburg  ...        Furniture    Bookcases   
2      Gaithersburg  ...       Technology       Phones   
3       Los Angeles  ...  Office Supplies      Storage   
4       San Antonio  ...       Technology  Accessories   
...             ...  ...              ...          ...   
5896  New York City  ...        Furniture    Bookcases   
5897      Fairfield  ...  Office Supplies      Binders   
5898       Loveland  ...  Office Supplies    Fasteners   
5899  New York City  ...  Office Supplies      Binders   
5900       Loveland  ...  Office Supplies    Fasteners   

                                           Product Name     Sales Quantity  \
0     Bush Westfield Collection Bookcases, Medium Ch...    73.940        1   
1     Bush Westfield Collection Bookcases, Medium Ch...   173.940        3   
2                                           GE 30522EE2   231.980        2   
3     Recycled Steel Personal File for Hanging File ...   114.460        2   
4                   Imation Clip USB flash drive - 8 GB    30.080        2   
...                                                 ...       ...      ...   
5896  Bush Westfield Collection Bookcases, Fully Ass...   213.136        4   
5897    Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl   295.904        2   
5898                                Bagged Rubber Bands   388.024        3   
5899               Wilson Jones Legal Size Ring Binders   462.776        3   
5900                                Bagged Rubber Bands  2975.510        3   

       Profit  Returns  Payment Mode  ind1  ind2  
0     28.2668      NaN        Online   NaN   NaN  
1     38.2668      NaN        Online   NaN   NaN  
2     67.2742      NaN         Cards   NaN   NaN  
3     28.6150      NaN        Online   NaN   NaN  
4     -5.2640      NaN        Online   NaN   NaN  
...       ...      ...           ...   ...   ...  
5896  12.1176      NaN           COD   NaN   NaN  
5897   4.5188      1.0        Online   NaN   NaN  
5898  -0.6048      NaN        Online   NaN   NaN  
5899  19.7910      NaN           COD   NaN   NaN  
5900  -0.6048      NaN           COD   NaN   

In [ ]:
pf.shape

(5901, 23)

In [ ]:
pf.columns

Index(['Row ID+O6G3A1:R6', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales', 'Quantity', 'Profit', 'Returns', 'Payment Mode', 'ind1',
       'ind2'],
      dtype='object')

In [ ]:
pf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5901 entries, 0 to 5900
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Row ID+O6G3A1:R6  5901 non-null   int64  
 1   Order ID          5901 non-null   object 
 2   Order Date        5901 non-null   object 
 3   Ship Date         5901 non-null   object 
 4   Ship Mode         5901 non-null   object 
 5   Customer ID       5901 non-null   object 
 6   Customer Name     5901 non-null   object 
 7   Segment           5901 non-null   object 
 8   Country           5901 non-null   object 
 9   City              5901 non-null   object 
 10  State             5901 non-null   object 
 11  Region            5901 non-null   object 
 12  Product ID        5901 non-null   object 
 13  Category          5901 non-null   object 
 14  Sub-Category      5901 non-null   object 
 15  Product Name      5901 non-null   object 
 16  Sales             5901 non-null   float64


In [25]:
#pf =pf.drop(["Row ID+O6G3A1:R6","Order ID","Order Date","Ship Date","Customer ID","Customer Name","City","State","Product Name","Sales","Quantity","Returns","ind1","ind2"], axis = 1)
#pf

In [24]:
pf

Ship Mode    Segment        Country   Region       Product ID  \
0     Standard Class  Corporate  United States     East  FUR-BO-10004709   
1     Standard Class  Corporate  United States     East  FUR-BO-10004709   
2     Standard Class  Corporate  United States     East  TEC-PH-10000455   
3        First Class   Consumer  United States     West  OFF-ST-10003692   
4     Standard Class  Corporate  United States  Central  TEC-AC-10002217   
...              ...        ...            ...      ...              ...   
5896  Standard Class   Consumer  United States     East  FUR-BO-10003441   
5897  Standard Class  Corporate  United States     West  OFF-BI-10002103   
5898  Standard Class   Consumer  United States     West  OFF-FA-10003472   
5899  Standard Class   Consumer  United States     East  OFF-BI-10003684   
5900  Standard Class   Consumer  United States     West  OFF-FA-10003472   

             Category Sub-Category   Profit Payment Mode  
0           Furniture    Bookcases  28.2668       Online  
1           Furniture    Bookcases  38.2668       Online  
2          Technology       Phones  67.2742        Cards  
3     Office Supplies      Storage  28.6150       Online  
4          Technology  Accessories  -5.2640       Online  
...               ...          ...      ...          ...  
5896        Furniture    Bookcases  12.1176          COD  
5897  Office Supplies      Binders   4.5188       Online  
5898  Office Supplies    Fasteners  -0.6048       Online  
5899  Office Supplies      Binders  19.7910          COD  
5900  Office Supplies    Fasteners  -0.6048          COD  

[5901 rows x 9 columns]

In [31]:
pf.isnull().sum()

Ship Mode       0
Segment         0
Country         0
Region          0
Product ID      0
Category        0
Sub-Category    0
Profit          0
Payment Mode    0
dtype: int64

In [28]:
pf.describe()

Profit
count  5901.000000
mean     29.700408
std     259.589138
min   -6599.978000
25%       1.795500
50%       8.502500
75%      28.615000
max    8399.976000

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
pf['Ship Mode'] = le.fit_transform(pf['Ship Mode'])
pf['Country'] = le.fit_transform(pf['Country'])
pf['Region'] = le.fit_transform(pf['Region'])
pf['Segment'] = le.fit_transform(pf['Segment'])
pf['Sub-Category'] = le.fit_transform(pf['Sub-Category'])
pf['Category'] = le.fit_transform(pf['Category'])
pf['Product ID'] = le.fit_transform(pf['Product ID'])
pf['Payment Mode'] = le.fit_transform(pf['Payment Mode'])
pf


Ship Mode  Segment  Country  Region  Product ID  Category  Sub-Category  \
0             3        1        0       1          44         0             4   
1             3        1        0       1          44         0             4   
2             3        1        0       1        1603         2            13   
3             0        0        0       3        1338         1            14   
4             3        1        0       0        1454         2             0   
...         ...      ...      ...     ...         ...       ...           ...   
5896          3        0        0       1          29         0             4   
5897          3        1        0       3         692         1             3   
5898          3        0        0       3         894         1             8   
5899          3        0        0       1         750         1             3   
5900          3        0        0       3         894         1             8   

       Profit  Payment Mode  
0     28.2668             2  
1     38.2668             2  
2     67.2742             1  
3     28.6150             2  
4     -5.2640             2  
...       ...           ...  
5896  12.1176             0  
5897   4.5188             2  
5898  -0.6048             2  
5899  19.7910             0  
5900  -0.6048             0  

[5901 rows x 9 columns]

In [35]:
x = pf.drop(['Profit'], axis = 1).values
y = pf['Profit'].values
x


array([[ 3,  1,  0, ...,  0,  4,  2],
       [ 3,  1,  0, ...,  0,  4,  2],
       [ 3,  1,  0, ...,  2, 13,  1],
       ...,
       [ 3,  0,  0, ...,  1,  8,  2],
       [ 3,  0,  0, ...,  1,  3,  0],
       [ 3,  0,  0, ...,  1,  8,  0]])

In [36]:
y

array([28.2668, 38.2668, 67.2742, ..., -0.6048, 19.791 , -0.6048])

In [37]:
from sklearn.preprocessing import StandardScaler
sr = StandardScaler()
sr.fit_transform(x)

array([[ 0.7134743 ,  0.40870188,  0.        , ..., -1.54753901,
        -0.70989435,  1.18772147],
       [ 0.7134743 ,  0.40870188,  0.        , ..., -1.54753901,
        -0.70989435,  1.18772147],
       [ 0.7134743 ,  0.40870188,  0.        , ...,  1.63712627,
         1.06631309,  0.05545259],
       ...,
       [ 0.7134743 , -0.88307625,  0.        , ...,  0.04479363,
         0.07953118,  1.18772147],
       [ 0.7134743 , -0.88307625,  0.        , ...,  0.04479363,
        -0.90725074, -1.07681629],
       [ 0.7134743 , -0.88307625,  0.        , ...,  0.04479363,
         0.07953118, -1.07681629]])

In [38]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, train_size= 0.3, random_state=117)

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [40]:
y_pred = lr.predict(x_test)
y_pred

array([ 21.56308512,  35.72945166,  63.90407831, ..., -30.01034326,
        17.83921318, 122.20166286])

In [41]:
y_test

array([ 1.824000e+01,  2.027100e+00, -6.599978e+03, ..., -3.255720e+02,
        1.593480e+01,  8.598280e+01])

In [42]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [43]:
mae = mean_absolute_error(y_test,y_pred)
mae

68.8447143816183

In [44]:
mse = mean_squared_error(y_test,y_pred)
mse

60712.52085220095

In [46]:
r2_score(y_test,y_pred)


0.002322671852164282